import Head from "next/head";
import { Inter } from "next/font/google";
import FeaturedPosts from "../components/home-page/featured-posts";
import Hero from "@/components/home-page/hero";
import { getFeaturedPosts } from "../lib/posts-util";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage(props) {
  return (
    <>
      <Head>
        <title>Alper Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedPosts posts={props.posts} />
    </>
  );
}

export function getStaticProps() {
  const featuredPosts = getFeaturedPosts();

  return {
    props: {
      posts: featuredPosts,
    },
  };
}
